[package]
name = "kb-hall"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15", features = ["default_font"] }
hidapi = "2.6"
log = "0.4"
tungstenite = "0.24"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
